server:
  port: 8086


spring:
  application:
    name: WALLET_SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/WalletSERVICE_DB
    username: root
    password: kalpesh@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
