server:
  port: 8084


spring:
  application:
    name: CART-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/cartservice_db
    username: root
    password: kalpesh@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
