server:
  port: 8080 # different for each service


spring:
  application:
    name: USER-SERVICE # change for each service
  datasource:
    url: jdbc:mysql://localhost:3306/userservice_db
    username: root
    password: kalpesh@123
  jpa:
     hibernate:
      ddl-auto: update
      show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
